apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-grafana
  namespace: kube-prometheus
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-prometheus
  project: default
  source:
    repoURL: 'git@github.com:minina0407/PortfoGram-k8s.git'  # 프로젝트의 Git 리포지토리 URL
    targetRevision: 'main'  # 또는 사용하는 브랜치 또는 커밋 해시
    path: 'helm/kube-prometheus-stack'  # 소스 코드 또는 Helm 차트가 있는 경로
    helm:
      valueFiles:
        - helm/kube-prometheus-stack/values.yaml  # Helm values 파일의 경로
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
