# Application Repository의 workflow
name: BuildAndPushImagesAndTriggerManifestUpdate

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_REPO: minimeisme/portfogram-argocd-k8s

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: source code checkout
        uses: actions/checkout@v3

      - name: Docker 레지스트리 로그인
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 서버 이미지 빌드 및 푸시
        id: build_and_push_server
        run: |
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          TAG="${COMMIT_HASH}" # 원하는 대로 태그를 지정할 수 있습니다.
          
          
          docker build -f Dockerfile -t minimeisme/portfogram-argocd-k8s:${TAG} \
            --build-arg MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --build-arg MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
            --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} .
          docker push minimeisme/portfogram-argocd-k8s:${TAG}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "::set-output name=TAG::${TAG}"
          

      - name: Manifest Repository workflow 트리거
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: minina0407/portfogram-mainfest
          event-type: update-manifest
          client-payload: '{"commit_hash": "${COMMIT_HASH}"}'
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
