name: BuildAndPushImagesAndTriggerManifestUpdate

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_REPO: minimeisme/portfogram-argocd-k8s

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: source code checkout
        uses: actions/checkout@v3

      - name: Docker 레지스트리 로그인
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 서버 이미지 빌드 및 푸시
        id: build_and_push_server
        run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:latest .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:latest

      - name: Manifest Repository workflow 트리거
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: https://github.com/minina0407/portfogram-mainfest.git
          event-type: update-manifest
          client-payload: '{"image_tag": "${{ env.IMAGE_REPO }}:latest"}'
